name: Build And Deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [entry.publish, entry.unpublish]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      STRAPI_URL: ${{ secrets.STRAPI_URL }}
      PUBLIC_STRAPI_URL: ${{ secrets.PUBLIC_STRAPI_URL }}
      STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
      PUBLIC_GOOGLE_RECAPTCHA_SECRET: ${{ secrets.PUBLIC_GOOGLE_RECAPTCHA_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.19.5

      - name: Installing dependencies
        run: npm ci

      - name: Building Site
        run: npm run build

      - name: Create plugin archive
        run: |
          # Create archive of only the plugin files (excluding .git, .github, etc.)
          zip -r dist.zip dist

      - name: Deploy via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "dist.zip"
          target: "tmp/"
          timeout: 60s
          command_timeout: 10m

      - name: Extract and install plugin
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          timeout: 60s
          command_timeout: 10m
          script: |
            set -euo pipefail

            BASE_DIR="$HOME/domains/mkti.pl/pulbic_html"
            ARCHIVE="$HOME/tmp/dist.zip"

            echo "Deploying to $BASE_DIR"

            cd "$BASE_DIR"

            # Extract the plugin from the correct location
            echo "Extracting archive from $ARCHIVE..."
            unzip -o "$ARCHIVE"
